types:
  EnrollmentAutomationsDeleteResponse:
    properties:
      ok: boolean
  EnrollmentAutomationsGetResponse:
    properties:
      enrollment_automation: root.EnrollmentAutomation
      ok: boolean
  EnrollmentAutomationsLaunchResponseEnrollmentAutomation:
    properties:
      acs_credential_provisioning_automation_id:
        type: string
        validation:
          format: uuid
      credential_manager_acs_system_id:
        type: string
        validation:
          format: uuid
      user_identity_id:
        type: string
        validation:
          format: uuid
      created_at: datetime
      workspace_id:
        type: string
        validation:
          format: uuid
      enrollment_automation_id:
        type: string
        validation:
          format: uuid
  EnrollmentAutomationsLaunchResponse:
    properties:
      enrollment_automation: EnrollmentAutomationsLaunchResponseEnrollmentAutomation
      ok: boolean
  EnrollmentAutomationsListResponse:
    properties:
      enrollment_automations: list<root.EnrollmentAutomation>
      ok: boolean
imports:
  root: ../__package__.yml
service:
  auth: false
  base-path: ''
  endpoints:
    delete:
      path: /user_identities/enrollment_automations/delete
      method: POST
      auth: true
      display-name: /user_identities/enrollment_automations/delete
      request:
        name: EnrollmentAutomationsDeleteRequest
        body:
          properties:
            enrollment_automation_id:
              type: string
              validation:
                format: uuid
      response:
        docs: OK
        type: EnrollmentAutomationsDeleteResponse
      errors:
        - root.BadRequestError
        - root.UnauthorizedError
      examples:
        - request:
            enrollment_automation_id: enrollment_automation_id
          response:
            body:
              ok: true
    get:
      path: /user_identities/enrollment_automations/get
      method: POST
      auth: true
      display-name: /user_identities/enrollment_automations/get
      request:
        name: EnrollmentAutomationsGetRequest
        body:
          properties:
            enrollment_automation_id:
              type: string
              validation:
                format: uuid
      response:
        docs: OK
        type: EnrollmentAutomationsGetResponse
        property: enrollment_automation
      errors:
        - root.BadRequestError
        - root.UnauthorizedError
      examples:
        - request:
            enrollment_automation_id: enrollment_automation_id
          response:
            body:
              enrollment_automation:
                credential_manager_acs_system_id: credential_manager_acs_system_id
                user_identity_id: user_identity_id
                created_at: '2024-01-15T09:30:00Z'
                workspace_id: workspace_id
                enrollment_automation_id: enrollment_automation_id
              ok: true
    launch:
      path: /user_identities/enrollment_automations/launch
      method: POST
      auth: true
      display-name: /user_identities/enrollment_automations/launch
      request:
        name: EnrollmentAutomationsLaunchRequest
        body:
          properties:
            user_identity_id:
              type: string
              validation:
                format: uuid
            credential_manager_acs_system_id:
              type: string
              validation:
                format: uuid
            acs_credential_pool_id:
              type: optional<string>
              validation:
                format: uuid
            create_credential_manager_user: optional<boolean>
            credential_manager_acs_user_id:
              type: optional<string>
              validation:
                format: uuid
      response:
        docs: OK
        type: EnrollmentAutomationsLaunchResponse
        property: enrollment_automation
      errors:
        - root.BadRequestError
        - root.UnauthorizedError
      examples:
        - request:
            user_identity_id: user_identity_id
            credential_manager_acs_system_id: credential_manager_acs_system_id
          response:
            body:
              enrollment_automation:
                acs_credential_provisioning_automation_id: acs_credential_provisioning_automation_id
                credential_manager_acs_system_id: credential_manager_acs_system_id
                user_identity_id: user_identity_id
                created_at: '2024-01-15T09:30:00Z'
                workspace_id: workspace_id
                enrollment_automation_id: enrollment_automation_id
              ok: true
    list:
      path: /user_identities/enrollment_automations/list
      method: POST
      auth: true
      display-name: /user_identities/enrollment_automations/list
      request:
        name: EnrollmentAutomationsListRequest
        body:
          properties:
            user_identity_id:
              type: string
              validation:
                format: uuid
      response:
        docs: OK
        type: EnrollmentAutomationsListResponse
        property: enrollment_automations
      errors:
        - root.BadRequestError
        - root.UnauthorizedError
      examples:
        - request:
            user_identity_id: user_identity_id
          response:
            body:
              enrollment_automations:
                - credential_manager_acs_system_id: credential_manager_acs_system_id
                  user_identity_id: user_identity_id
                  created_at: '2024-01-15T09:30:00Z'
                  workspace_id: workspace_id
                  enrollment_automation_id: enrollment_automation_id
              ok: true
