openapi: openapi/openapi.json
openapi-overrides: openapi/overrides.yml
groups:
  java-sdk:
    generators:
      - name: fernapi/fern-java-sdk
        version: 0.9.6
        output:
          location: maven
          coordinate: io.github.seamapi:java
          username: ${MAVEN_USERNAME}
          password: ${MAVEN_PASSWORD}
        github:
          repository: seamapi/java
          mode: pull-request
        config:
          client-class-name: Seam
          custom-dependencies:
            - "testImplementation org.assertj:assertj-core:3.24.2"
  go-sdk:
    generators:
      - name: fernapi/fern-go-sdk
        version: 0.17.0
        github:
          repository: seamapi/go
          mode: pull-request
        config: 
          includeLegacyClientOptions: true
      
