imports:
  root: ../__package__.yml
types:
  CredentialProvisioningAutomationsLaunchResponse:
    properties:
      acs_credential_provisioning_automation: root.AcsCredentialProvisioningAutomation
      ok: boolean
service:
  auth: false
  base-path: ''
  endpoints:
    launch:
      path: /acs/credential_provisioning_automations/launch
      method: POST
      auth: true
      display-name: /acs/credential_provisioning_automations/launch
      request:
        name: CredentialProvisioningAutomationsLaunchRequest
        body:
          properties:
            user_identity_id:
              type: string
              validation:
                format: uuid
            credential_manager_acs_system_id:
              type: string
              validation:
                format: uuid
            acs_credential_pool_id:
              type: optional<string>
              validation:
                format: uuid
            create_credential_manager_user: optional<boolean>
            credential_manager_acs_user_id:
              type: optional<string>
              validation:
                format: uuid
      response:
        docs: OK
        type: CredentialProvisioningAutomationsLaunchResponse
        property: acs_credential_provisioning_automation
      errors:
        - root.BadRequestError
        - root.UnauthorizedError
      examples:
        - request:
            user_identity_id: user_identity_id
            credential_manager_acs_system_id: credential_manager_acs_system_id
          response:
            body:
              acs_credential_provisioning_automation:
                acs_credential_provisioning_automation_id: acs_credential_provisioning_automation_id
                credential_manager_acs_system_id: credential_manager_acs_system_id
                user_identity_id: user_identity_id
                created_at: '2024-01-15T09:30:00Z'
                workspace_id: workspace_id
              ok: true
