imports:
  root: ../__package__.yml
types:
  ServiceByServiceNameResponse:
    properties:
      ok: boolean
      last_service_evaluation_at: string
      service_health: root.ServiceHealth
service:
  auth: false
  base-path: ''
  endpoints:
    by_service_name:
      path: /health/service/[service_name]
      method: POST
      auth: false
      display-name: /health/service/[service_name]
      request:
        name: ServiceByServiceNameRequest
        body:
          properties:
            service_name: string
      response:
        docs: OK
        type: ServiceByServiceNameResponse
      errors:
        - root.BadRequestError
        - root.UnauthorizedError
      examples:
        - request:
            service_name: service_name
          response:
            body:
              ok: true
              last_service_evaluation_at: last_service_evaluation_at
              service_health:
                service: service
                status: healthy
                description: description
