types:
  ClimateSettingSchedulesCreateRequestHvacModeSetting:
    enum:
      - 'off'
      - heat
      - cool
      - heat_cool
  ClimateSettingSchedulesCreateResponse:
    properties:
      climate_setting_schedule: root.ClimateSettingSchedule
      ok: boolean
  ClimateSettingSchedulesDeleteResponse:
    properties:
      ok: boolean
  ClimateSettingSchedulesGetResponse:
    properties:
      climate_setting_schedule: root.ClimateSettingSchedule
      ok: boolean
  ClimateSettingSchedulesListResponse:
    properties:
      climate_setting_schedules: list<root.ClimateSettingSchedule>
      ok: boolean
  ClimateSettingSchedulesUpdateRequestHvacModeSetting:
    enum:
      - 'off'
      - heat
      - cool
      - heat_cool
  ClimateSettingSchedulesUpdateResponse:
    properties:
      climate_setting_schedule: root.ClimateSettingSchedule
      ok: boolean
imports:
  root: ../__package__.yml
service:
  auth: false
  base-path: ''
  endpoints:
    create:
      path: /thermostats/climate_setting_schedules/create
      method: POST
      auth: true
      display-name: /thermostats/climate_setting_schedules/create
      request:
        name: ClimateSettingSchedulesCreateRequest
        body:
          properties:
            schedule_type: optional<literal<"time_bound">>
            device_id: string
            name: optional<string>
            schedule_starts_at: string
            schedule_ends_at: string
            automatic_heating_enabled: optional<boolean>
            automatic_cooling_enabled: optional<boolean>
            hvac_mode_setting: optional<ClimateSettingSchedulesCreateRequestHvacModeSetting>
            cooling_set_point_celsius: optional<double>
            heating_set_point_celsius: optional<double>
            cooling_set_point_fahrenheit: optional<double>
            heating_set_point_fahrenheit: optional<double>
            manual_override_allowed: optional<boolean>
      response:
        docs: OK
        type: ClimateSettingSchedulesCreateResponse
        property: climate_setting_schedule
      errors:
        - root.BadRequestError
        - root.UnauthorizedError
      examples:
        - request:
            device_id: device_id
            schedule_starts_at: schedule_starts_at
            schedule_ends_at: schedule_ends_at
          response:
            body:
              climate_setting_schedule:
                climate_setting_schedule_id: climate_setting_schedule_id
                schedule_type: time_bound
                device_id: device_id
                name: name
                schedule_starts_at: schedule_starts_at
                schedule_ends_at: schedule_ends_at
                created_at: '2024-01-15T09:30:00Z'
                errors:
                  key: value
                automatic_heating_enabled: true
                automatic_cooling_enabled: true
                hvac_mode_setting: 'off'
                cooling_set_point_celsius: 1.1
                heating_set_point_celsius: 1.1
                cooling_set_point_fahrenheit: 1.1
                heating_set_point_fahrenheit: 1.1
                manual_override_allowed: true
              ok: true
    delete:
      path: /thermostats/climate_setting_schedules/delete
      method: POST
      auth: true
      display-name: /thermostats/climate_setting_schedules/delete
      request:
        name: ClimateSettingSchedulesDeleteRequest
        body:
          properties:
            climate_setting_schedule_id: string
      response:
        docs: OK
        type: ClimateSettingSchedulesDeleteResponse
      errors:
        - root.BadRequestError
        - root.UnauthorizedError
      examples:
        - request:
            climate_setting_schedule_id: climate_setting_schedule_id
          response:
            body:
              ok: true
    get:
      path: /thermostats/climate_setting_schedules/get
      method: POST
      auth: true
      display-name: /thermostats/climate_setting_schedules/get
      request:
        name: ClimateSettingSchedulesGetRequest
        body:
          properties:
            climate_setting_schedule_id: optional<string>
            device_id: optional<string>
      response:
        docs: OK
        type: ClimateSettingSchedulesGetResponse
        property: climate_setting_schedule
      errors:
        - root.BadRequestError
        - root.UnauthorizedError
      examples:
        - request: {}
          response:
            body:
              climate_setting_schedule:
                climate_setting_schedule_id: climate_setting_schedule_id
                schedule_type: time_bound
                device_id: device_id
                name: name
                schedule_starts_at: schedule_starts_at
                schedule_ends_at: schedule_ends_at
                created_at: '2024-01-15T09:30:00Z'
                errors:
                  key: value
                automatic_heating_enabled: true
                automatic_cooling_enabled: true
                hvac_mode_setting: 'off'
                cooling_set_point_celsius: 1.1
                heating_set_point_celsius: 1.1
                cooling_set_point_fahrenheit: 1.1
                heating_set_point_fahrenheit: 1.1
                manual_override_allowed: true
              ok: true
    list:
      path: /thermostats/climate_setting_schedules/list
      method: POST
      auth: true
      display-name: /thermostats/climate_setting_schedules/list
      request:
        name: ClimateSettingSchedulesListRequest
        body:
          properties:
            device_id: string
            user_identifier_key: optional<string>
      response:
        docs: OK
        type: ClimateSettingSchedulesListResponse
        property: climate_setting_schedules
      errors:
        - root.BadRequestError
        - root.UnauthorizedError
      examples:
        - request:
            device_id: device_id
          response:
            body:
              climate_setting_schedules:
                - climate_setting_schedule_id: climate_setting_schedule_id
                  schedule_type: time_bound
                  device_id: device_id
                  name: name
                  schedule_starts_at: schedule_starts_at
                  schedule_ends_at: schedule_ends_at
                  created_at: '2024-01-15T09:30:00Z'
                  errors:
                    key: value
                  automatic_heating_enabled: true
                  automatic_cooling_enabled: true
                  hvac_mode_setting: 'off'
                  cooling_set_point_celsius: 1.1
                  heating_set_point_celsius: 1.1
                  cooling_set_point_fahrenheit: 1.1
                  heating_set_point_fahrenheit: 1.1
                  manual_override_allowed: true
              ok: true
    update:
      path: /thermostats/climate_setting_schedules/update
      method: POST
      auth: true
      display-name: /thermostats/climate_setting_schedules/update
      request:
        name: ClimateSettingSchedulesUpdateRequest
        body:
          properties:
            climate_setting_schedule_id: string
            schedule_type: optional<literal<"time_bound">>
            name: optional<string>
            schedule_starts_at: optional<string>
            schedule_ends_at: optional<string>
            automatic_heating_enabled: optional<boolean>
            automatic_cooling_enabled: optional<boolean>
            hvac_mode_setting: optional<ClimateSettingSchedulesUpdateRequestHvacModeSetting>
            cooling_set_point_celsius: optional<double>
            heating_set_point_celsius: optional<double>
            cooling_set_point_fahrenheit: optional<double>
            heating_set_point_fahrenheit: optional<double>
            manual_override_allowed: optional<boolean>
      response:
        docs: OK
        type: ClimateSettingSchedulesUpdateResponse
        property: climate_setting_schedule
      errors:
        - root.BadRequestError
        - root.UnauthorizedError
      examples:
        - request:
            climate_setting_schedule_id: climate_setting_schedule_id
          response:
            body:
              climate_setting_schedule:
                climate_setting_schedule_id: climate_setting_schedule_id
                schedule_type: time_bound
                device_id: device_id
                name: name
                schedule_starts_at: schedule_starts_at
                schedule_ends_at: schedule_ends_at
                created_at: '2024-01-15T09:30:00Z'
                errors:
                  key: value
                automatic_heating_enabled: true
                automatic_cooling_enabled: true
                hvac_mode_setting: 'off'
                cooling_set_point_celsius: 1.1
                heating_set_point_celsius: 1.1
                cooling_set_point_fahrenheit: 1.1
                heating_set_point_fahrenheit: 1.1
                manual_override_allowed: true
              ok: true
